src/main/java/br/gov/mt/indea/passagens/managedbeans/LoginManagedBean.java
package br.gov.mt.indea.passagens.managedbeans;

import java.io.IOException;
import java.io.Serializable;
import java.net.ConnectException;

import javax.enterprise.context.SessionScoped;
import javax.faces.FacesException;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.security.authentication.AccountExpiredException;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.LockedException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.web.WebAttributes;

import com.ocpsoft.pretty.faces.annotation.URLBeanName;
import com.ocpsoft.pretty.faces.annotation.URLMapping;
import com.ocpsoft.pretty.faces.annotation.URLMappings;

import br.gov.mt.indea.passagens.security.UserSecurity;
import br.gov.mt.indea.passagens.util.ExceptionUtil;
import br.gov.mt.indea.passagens.util.FacesMessageUtil;
import br.gov.mt.indea.passagens.util.FacesUtil;

@Named("loginManagedBean")
@SessionScoped
@URLBeanName("loginManagedBean")
@URLMappings(mappings = {
		@URLMapping(id = "login", pattern = "/login", viewId = "/login.jsf")})
public class LoginManagedBean implements Serializable {

	private static final long serialVersionUID = -7990403902080061184L;

	@Inject
	private FacesContext context;

	@Inject
	private HttpServletRequest request;

	@Inject
	private HttpServletResponse response;
	
	public void preRender() {
		if ("true".equals(request.getParameter("failed"))) {
			Exception ex = (Exception) FacesContext.getCurrentInstance().getExternalContext().getSessionMap()
					.get(WebAttributes.AUTHENTICATION_EXCEPTION);

			if (ex != null) {

				if (ex instanceof BadCredentialsException)
					FacesMessageUtil.addInfoFacesMessage(null, "Usuário ou senha inválidos", "");
				else if (ex instanceof AccountExpiredException)
					FacesMessageUtil.addInfoFacesMessage(null, "Usuário expirado", "Entre em contato com o administrador do sistema");
				else if (ex instanceof LockedException)
					FacesMessageUtil.addInfoFacesMessage(null, "Usuário inativo", "Entre em contato com o administrador do sistema");
				else{
					Throwable findException = ExceptionUtil.findException(ex, ConnectException.class);
					if (findException != null){
						FacesMessageUtil.addErrorFacesMessage(null, "Não foi possível conectar com o banco de dados.", "Entre em contato com o administrador");
					} else
						FacesMessageUtil.addErrorFacesMessage(null, "Erro ao tentar realizar login", "Causa: " + ex.getMessage());
				}

			}
		}
	}
	
	public void redirect() throws FacesException, IOException{
		if (this.isUsuarioAutenticado()){
			FacesUtil.doRedirect(FacesContext.getCurrentInstance(), "/dashboard");
		} else
			return;
	}

	public void login() throws ServletException, IOException {
		RequestDispatcher dispatcher = request.getRequestDispatcher("/login");
		dispatcher.forward(request, response);

		context.responseComplete();
	}

	public boolean isUsuarioAutenticado() {
		return this.getUserSecurity() != null;
	}

	public UserSecurity getUserSecurity() {
		UserSecurity userSecurity = null;

		UsernamePasswordAuthenticationToken userPrincipal = (UsernamePasswordAuthenticationToken) context
				.getExternalContext().getUserPrincipal();

		if (userPrincipal != null && userPrincipal.getPrincipal() != null)
			userSecurity = (UserSecurity) userPrincipal.getPrincipal();

		return userSecurity;
	}
	
	public void keepAlive(){
	}
	
}

src/main/webapp/resources/templates/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<f:loadBundle var="messages" basename="messages" />

<h:head>
	<title>Passagens</title>
	<h:outputStylesheet name="style.css" library="css" />
	<h:outputStylesheet name="table_gradient.css" library="css" />
	<h:outputStylesheet name="widths.css" library="css" />
	<h:outputStylesheet name="icons.css" library="css" />

	<h:outputStylesheet library="primefaces" name="components.css" />
	<h:outputScript library="primefaces" name="core.js" />
	<h:outputScript library="primefaces" name="components.js" />
	<h:outputScript library="primefaces" name="jquery/jquery-plugins.js" />

	<style>
ul.ui-menu-child {
	width: 175px !important;
}
</style>

	<link href="https://fonts.googleapis.com/css?family=Antic+Slab"
		rel="stylesheet" />
	<link rel="shortcut icon" type="image/x-icon"
		href="#{request.contextPath}/resources/img/favicon/favicon.png" />

	<script
		src="#{facesContext.externalContext.requestContextPath}/resources/js/locale-primefaces.js"
		type="text/javascript" />

	<script
		src="#{facesContext.externalContext.requestContextPath}/resources/js/jquery.limit-1.3.js"
		type="text/javascript" />
	<script
		src="#{facesContext.externalContext.requestContextPath}/resources/js/jquery.maskedinput-1.2.2.min.js"
		type="text/javascript" />
	<script
		src="#{facesContext.externalContext.requestContextPath}/resources/js/jquery.price_format.1.5.js"
		type="text/javascript" />
	<script
		src="#{facesContext.externalContext.requestContextPath}/resources/js/jquery.alphanumeric.js"
		type="text/javascript" />
	<script
		src="#{facesContext.externalContext.requestContextPath}/resources/js/javascript.js"
		type="text/javascript" />

	<script type="text/JavaScript">
		  function up(lstr){
		    var str=lstr.value;
		    lstr.value=str.toUpperCase();
		  }
		  function down(lstr){
		    var str=lstr.value;
		    lstr.value=str.toLowerCase();
		  }
		  
		  function numericFilter(txb) {
			txb.value = txb.value.replace(/\D/g,"");
		  }

		  function focusElement(id){
			var e = document.getElementById(id);
			e.focus();
		  }

		  function hideDialogAfterSuccess(args, dialog){
			if (args &amp;&amp; !args.validationFailed)
				dialog.hide();
		  }

		  function moeda(z){  
			v = z.value;
			v = v.replace(/\D/g,"")  //permite digitar apenas números
			v = v.replace(/[0-9]{12}/,"inválido")   //limita pra máximo 999.999.999,99
			v = v.replace(/(\d{1})(\d{8})$/,"$1.$2")  //coloca ponto antes dos últimos 8 digitos
			v = v.replace(/(\d{1})(\d{5})$/,"$1.$2")  //coloca ponto antes dos últimos 5 digitos
			v = v.replace(/(\d{1})(\d{1,2})$/,"$1:$2")        //coloca virgula antes dos últimos 2 digitos
			z.value = v;
		  }


		  function mascara_telefone(o){
				v_obj=o
				v_fun=mtel
				setTimeout("execmascara()",1)
			}
			function execmascara(){
				v_obj.value=v_fun(v_obj.value)
			}
			function mtel(v){
				v=v.replace(/\D/g,"");//Remove tudo o que não é dígito
				v=v.replace(/^(\d{2})(\d)/g,"($1) $2");//Coloca parênteses em volta dos dois primeiros dígitos
				v=v.replace(/(\d)(\d{4})$/,"$1-$2");//Coloca hífen entre o quarto e o quinto dígitos
				return v;
			}
			function id( el ){
				return document.getElementById( el );
			}
					  
	  </script>

	<script type="text/javascript">
	  	window.history.forward();
	   	function noBack() { window.history.forward(); }
	  </script>

	<ui:insert name="head" />
</h:head>
<h:body onload="noBack();" onpageshow="if (event.persisted) noBack();"
	onunload="">

	<p:outputPanel id="pgrowl" ajaxRendered="true"> 
		<p:growl id="growl" sticky="false" showSummary="true"
			showDetail="true" globalOnly="false" autoUpdate="true" />
	</p:outputPanel>

	<div id="geral">

		<div id="header">
			<div style="width: 1050px; margin: auto;">
				<div id="contentHeader">
					<img src="#{resource['img/logos/bus_ticket.png']}" alt="" height="80px" width="80px"/>
					<div style="font-family: 'Antic Slab', serif">
						<div style="font-size: 40px; font-weight: bold;">Passagens</div>
						<div style="font-size: 20px;">Sistema de emissão de passagens - Indea MT</div>
					</div>
				</div>
			</div>
			​
		</div>

		<div id="content">
			<div id="formulario">
				<h:form>
					<p:menubar rendered="#{loginManagedBean.usuarioAutenticado}">
						<p:menuitem value="Dashboard" url="/passagens/dashboard" />

						<p:submenu label="Viagem">
							<p:menuitem value="Pesquisar" url="/passagens/viagem/pesquisar" />
							<p:menuitem value="Nova" url="/passagens/viagem/incluir" />
							<p:menuitem value="Autorização da Coordenadoria Demandante"
								url="/passagens/aprovarreprovar/pesquisar" />
							<p:menuitem value="Autorização da COPAS"
								url="/passagens/autorizarnaoautorizar/pesquisar" />
						</p:submenu>

						<p:submenu label="Painel de administração"
							rendered="#{loginManagedBean.userSecurity.hasAuthorityAdmin()}">
							<p:submenu label="Controle de acesso">
								<p:menuitem value="Usuários" url="/passagens/usuario/pesquisar" />
								<p:menuitem value="Grupos" url="/passagens/grupo/pesquisar" />
								<p:menuitem value="Permissões"
									url="/passagens/permissao/pesquisar" />
							</p:submenu>

							<p:submenu label="Cadastros auxiliares">
								<p:menuitem value="Autorizador"
									url="/passagens/autorizador/pesquisar" />
								<p:menuitem value="Contrato"
									url="/passagens/contrato/visualizar" />
								<p:menuitem value="Coordenadoria Demandante"
									url="/passagens/coordenadoriaDemandante/pesquisar" />
								<p:menuitem value="Fonte Pagamento"
									url="/passagens/fontepagamento/pesquisar" />
							</p:submenu>
						</p:submenu>




						<f:facet name="options">
							<p:menuButton
								value="#{loginManagedBean.userSecurity.usuario.primeiroNome}">
								<p:menuitem value="Dados da conta" action="pretty:selfUsuario" />
								<p:menuitem value="Logout" url="/passagens/logout" />
							</p:menuButton>
						</f:facet>

					</p:menubar>

					<p:menubar rendered="#{not loginManagedBean.usuarioAutenticado}">
						<p:menuitem value="Área restrita" url="/passagens/login" />

						<p:menuitem value="Validar viagem" url="/passagens/validar" />
					</p:menubar>
				</h:form>
				<br />

				<ui:insert name="body" />
			</div>

			<div style="padding-left: 25px; padding-right: 25px">
				<ui:insert name="bodyFull" />
			</div>
		</div>



		<div id="footer">Versão #{messages.version} #{messages.state}</div>

	</div>

	<p:ajaxStatus
		style="width:64px;height:64px;position:fixed;right:5px;bottom:5px">
		<f:facet name="start">
			<p:graphicImage value="/resources/img/ajax-loader.gif" />
		</f:facet>

		<f:facet name="complete">
			<h:outputText value="" />
		</f:facet>
	</p:ajaxStatus>

	<p:ajaxStatus onstart="PF('statusDialog').show()"
		onsuccess="PF('statusDialog').hide()" />

	<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
		closable="false" resizable="false" showHeader="false">
		<p:graphicImage value="/resources/img/ajax-loader.gif" />
	</p:dialog>

</h:body>
</html>

src/main/webapp/resources/templates/template_timeout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	
	<ui:decorate template="/resources/templates/template.xhtml">

		

    </ui:decorate>
    
    <ui:include src="/resources/componentes/sessionTimeOut.xhtml" />
    
</html>