src/main/java/br/gov/mt/indea/passagens/entity/passagens/CoordenadoriaDemandante.java
package br.gov.mt.indea.passagens.entity.passagens;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

import br.gov.mt.indea.passagens.entity.dbindea.Unidade;
import br.gov.mt.indea.passagens.enums.Dominio.AtivoInativo;

@Audited
@Entity
@Table(name = "coordenadoria_demandante")
public class CoordenadoriaDemandante extends BaseEntity<Long> implements Serializable{

	private static final long serialVersionUID = -8530781402902841303L;

	@Id
	@SequenceGenerator(name="coordenadoria_demandante_seq", sequenceName="coordenadoria_demandante_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="coordenadoria_demandante_seq")
	private Long id;
	
	@Column(name="data_cadastro")
	private LocalDateTime dataCadastro;
	
	@Column(name="id_unidade", length = 255)
	private String idUnidade;
	
	@Column(name="nome_unidade", length = 255)
	private String nomeUnidade;
	
	@Transient
	private Unidade unidade;
	
	@ManyToOne(cascade = {CascadeType.DETACH, CascadeType.REFRESH}, fetch = FetchType.EAGER)
	@JoinColumn(name = "id_usuario_responsavel")
	private Usuario usuarioResponsavel;
	
	@Enumerated(EnumType.STRING)
	@Column(name="status")
	private AtivoInativo status = AtivoInativo.ATIVO;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public LocalDateTime getDataCadastro() {
		return dataCadastro;
	}

	public void setDataCadastro(LocalDateTime dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public String getIdUnidade() {
		return idUnidade;
	}

	public void setIdUnidade(String idUnidade) {
		this.idUnidade = idUnidade;
	}

	public String getNomeUnidade() {
		return nomeUnidade;
	}

	public void setNomeUnidade(String nomeUnidade) {
		this.nomeUnidade = nomeUnidade;
	}

	public Unidade getUnidade() {
		return unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.idUnidade = unidade.getId() + "";
		this.nomeUnidade = unidade.getNome();
		this.unidade = unidade;
	}

	public Usuario getUsuarioResponsavel() {
		return usuarioResponsavel;
	}

	public void setUsuarioResponsavel(Usuario usuarioResponsavel) {
		this.usuarioResponsavel = usuarioResponsavel;
	}

	public AtivoInativo getStatus() {
		return status;
	}

	public void setStatus(AtivoInativo status) {
		this.status = status;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CoordenadoriaDemandante other = (CoordenadoriaDemandante) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
}

src/main/java/br/gov/mt/indea/passagens/managedbeans/AprovarReprovarManagedBean.java
package br.gov.mt.indea.passagens.managedbeans;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.ocpsoft.pretty.faces.annotation.URLAction;
import com.ocpsoft.pretty.faces.annotation.URLBeanName;
import com.ocpsoft.pretty.faces.annotation.URLMapping;
import com.ocpsoft.pretty.faces.annotation.URLMappings;

import br.gov.mt.indea.passagens.entity.dbindea.Servidor;
import br.gov.mt.indea.passagens.entity.dto.ViagemDTO;
import br.gov.mt.indea.passagens.entity.passagens.CoordenadoriaDemandante;
import br.gov.mt.indea.passagens.entity.passagens.FontePagamento;
import br.gov.mt.indea.passagens.entity.passagens.Viagem;
import br.gov.mt.indea.passagens.enums.Dominio.Status;
import br.gov.mt.indea.passagens.security.UserSecurity;
import br.gov.mt.indea.passagens.service.CoordenadoriaDemandanteService;
import br.gov.mt.indea.passagens.service.FontePagamentoService;
import br.gov.mt.indea.passagens.service.LazyObjectDataModel;
import br.gov.mt.indea.passagens.service.ServidorService;
import br.gov.mt.indea.passagens.service.ViagemService;
import br.gov.mt.indea.passagens.util.FacesMessageUtil;

@Named
@ViewScoped
@URLBeanName("aprovarReprovarManagedBean")
@URLMappings(mappings = {
		@URLMapping(id = "pesquisarAprovarReprovar", pattern = "/aprovarreprovar/pesquisar", viewId = "/pages/aprovarreprovar/lista.jsf"),
		@URLMapping(id = "permissoesAprovarReprovar", pattern = "/aprovarreprovar/#{aprovarReprovarManagedBean.id}/permissoes", viewId = "/pages/aprovarreprovar/permissoes.jsf")})
public class AprovarReprovarManagedBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2604643337140244881L;

	private LazyObjectDataModel<Viagem> listaViagem;
	
	private List<Servidor> listaServidores;
	
	private List<FontePagamento> listaFontePagamentos;
	
	private String motivo;
	
	@Inject
	private Viagem viagemSelecionada;
	
	private Long viagemSelecionadaId;

	@Inject
	private ViagemDTO viagemDTO;
	
	@Inject
	private ViagemService viagemService;
	
	@Inject
	private ServidorService servidorService;
	
	@Inject
	private FontePagamentoService fontePagamentoService;
	
	@Inject
	private CoordenadoriaDemandanteService coordenadoriaDemandanteService;
	
	@Inject
	private UserSecurity userSecurity;
	
	private boolean editando;
	
	private Long id;
	
	@PostConstruct
	private void init(){
		listaFontePagamentos = fontePagamentoService.findAll();
		
	}
	
	public void limpar(){
	}
	
	public void buscarViagens(){
		if (this.viagemDTO.getCoordenadoriaDemandante() == null)
			this.viagemDTO.setListaCoordenadoriaDemandante(this.getListaCoordenadoriaDemandante());
		else
			this.viagemDTO.setListaCoordenadoriaDemandante(null);
		
		this.listaViagem = new LazyObjectDataModel<Viagem>(this.viagemService, this.viagemDTO);
		
	}
	
	public List<Servidor> buscarServidor(String query){
		
		listaServidores = servidorService.findByNome(query);
		return listaServidores;
	}

	@URLAction(mappingId = "pesquisarAprovarReprovar", onPostback = false)
	public void pesquisar(){
		limpar();

		this.viagemDTO = new ViagemDTO();
		this.viagemDTO.setStatus(Status.NOVA);
		this.buscarViagens();

	}
	
	public void aprovar() {
		this.viagemSelecionada.setStatus(Status.AUTORIZADA_COORDENADORIA);
		this.viagemSelecionada.setDataAprovacao(LocalDateTime.now());
		this.viagemSelecionada.setUsuarioAprovacao(userSecurity.getUsuario());
		this.viagemSelecionada.getFontePagamento();
		viagemService.saveOrUpdate(this.viagemSelecionada);
		
		FacesMessageUtil.addInfoContextFacesMessage("Passagem autorizada com sucesso", "");
	}
	
	public void reprovar() {
		this.viagemSelecionada.setStatus(Status.NAO_AUTORIZADA_COORDENADORIA);
		this.viagemSelecionada.setDataAprovacao(LocalDateTime.now());
		this.viagemSelecionada.setUsuarioAprovacao(userSecurity.getUsuario());
		viagemService.saveOrUpdate(this.viagemSelecionada);
		
		FacesMessageUtil.addInfoContextFacesMessage("Passagem reprovada com sucesso", "");
	}

	public void abrirTelaAprovarViagem(Viagem viagem) {
		this.setViagemSelecionada(viagemService.findById(viagem.getId()));
	}
	
	public void abrirTelaReprovarViagem(Viagem viagem) {
		this.setViagemSelecionada(viagem);
	}
	
	public List<CoordenadoriaDemandante> getListaCoordenadoriaDemandante(){
		return this.coordenadoriaDemandanteService.findAllAtivosBy(this.userSecurity.getUsuario());
	}

	public LazyObjectDataModel<Viagem> getListaViagem() {
		return listaViagem;
	}

	public void setListaViagem(LazyObjectDataModel<Viagem> listaViagem) {
		this.listaViagem = listaViagem;
	}

	public Viagem getViagemSelecionada() {
		return viagemSelecionada;
	}

	public void setViagemSelecionada(Viagem viagem) {
		this.viagemSelecionada = viagem;
	}

	public ViagemService getViagemService() {
		return viagemService;
	}

	public void setViagemService(ViagemService viagemService) {
		this.viagemService = viagemService;
	}

	public ViagemDTO getViagemDTO() {
		return viagemDTO;
	}

	public void setViagemDTO(ViagemDTO viagemDTO) {
		this.viagemDTO = viagemDTO;
	}

	public boolean isEditando() {
		return editando;
	}

	public void setEditando(boolean editando) {
		this.editando = editando;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<Servidor> getListaServidores() {
		return listaServidores;
	}

	public void setListaServidores(List<Servidor> listaServidores) {
		this.listaServidores = listaServidores;
	}

	public List<FontePagamento> getListaFontePagamentos() {
		return listaFontePagamentos;
	}

	public void setListaFontePagamentos(List<FontePagamento> listaFontePagamentos) {
		this.listaFontePagamentos = listaFontePagamentos;
	}

	public String getMotivo() {
		return motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public Long getViagemSelecionadaId() {
		return viagemSelecionadaId;
	}

	public void setViagemSelecionadaId(Long viagemSelecionadaId) {
		this.viagemSelecionadaId = viagemSelecionadaId;
	}
}

src/main/webapp/pages/coordenadoriaDemandante/lista.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"	
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:o="http://java.sun.com/jsf/composite/componentes"
	xmlns:p="http://primefaces.org/ui">

	<ui:composition template="/resources/templates/template_timeout.xhtml">
		
		<ui:define name="body">
			
			<h:form id="formListaCoordenadoriaDemandantes" enctype="multipart/form-data">
			
				<h1>Coordenadorias Demandantes</h1>
			
				<p:messages id="pmessages"/>
			
				<p:dataTable emptyMessage="Nenhum registro" 
						value="#{coordenadoriaDemandanteManagedBean.listaCoordenadoriaDemandante}" 
						var="coordenadoriaDemandante" 
						id="tableCoordenadoriaDemandantes">
							
					<p:column headerText="Coordenadoria"
							style="width: 45%">
						#{coordenadoriaDemandante.nomeUnidade}
					</p:column>
					
					<p:column headerText="Responsável">
						#{coordenadoriaDemandante.usuarioResponsavel.nome}
					</p:column>
					
					<p:column headerText="Status"
							style="width: 5%">
						<p:toggleSwitch value="#{coordenadoriaDemandante.status}" converter="ativoInativoConverter">
				            <p:ajax listener="#{coordenadoriaDemandanteManagedBean.atualizarStatus(coordenadoriaDemandante)}"
				            		process="@all" 
				            		update="@all" />
				        </p:toggleSwitch>
					</p:column>
					
					<p:column style="width: 10%; text-align: right" >
						<f:facet name="header">
							<p:commandButton icon="ui-icon-customadd"
									onclick="this.form.target='_self'" 
									action="pretty:incluirCoordenadoriaDemandante"
									ajax="false" 
									title="Novo"/>
						</f:facet>
					
						<p:commandButton icon="ui-icon-customedit"
								action="pretty:alterarCoordenadoriaDemandante" 
								title="Editar" 
								onclick="this.form.target='_self'">
            				<f:setPropertyActionListener target="#{coordenadoriaDemandanteManagedBean.id}" value="#{coordenadoriaDemandante.id}" />
						</p:commandButton>
					
						<p:dialog widgetVar="statusDialog2" modal="true" draggable="false" closable="false" resizable="false" showHeader="false">
					    	<p:graphicImage value="/resources/img/ajax-loader.gif" />
					  	</p:dialog>
						
					</p:column>
				</p:dataTable>
				
			</h:form>
		</ui:define>
	</ui:composition>
</html>